### ISSUE TITLE
depracation warning for mis-using Cistern::Service

### ISSUE THREAD

**Issue by betesh** [lanej/zendesk2#36]
subclassing Cistern::Service is deprecated.  Please use `include Cistern::Client`.
    (zendesk2-1.7.1/lib/zendesk2/client.rb:1:in `<top (required)>')

**Comment by lanej** [comment]
Fixed by https://github.com/lanej/zendesk2/commit/f77d096afc15ee4a8e83bc7f94efc14f03672eef
